"""add price

Revision ID: 567c22510d30
Revises: 9b10561b56a0
Create Date: 2024-04-03 10:22:48.934904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567c22510d30'
down_revision = '9b10561b56a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examples', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
